apiVersion: v2
name: monitoring
description: A Helm chart which configures prometheus monitoring components for an application deployed on openshift
type: application
version: 0.1.0
appVersion: "1.0.0"
