name: Publish Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write 

jobs:
  publish:
    name: Lint, Package, and Publish
    runs-on: ubuntu-latest

    env:
      CHART_PATH: . 

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 2. Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.2'

      - name: 3. Get Chart Info
        id: chart_info
        run: |
          CHART_NAME=$(grep '^name:' ${{ env.CHART_PATH }}/Chart.yaml | awk '{print $2}')
          CHART_VERSION=$(grep '^version:' ${{ env.CHART_PATH }}/Chart.yaml | awk '{print $2}')
          
          echo "::set-output name=name::$CHART_NAME"
          echo "::set-output name=version::$CHART_VERSION"
          echo "Publishing $CHART_NAME version $CHART_VERSION"

      - name: 4. Lint Helm Chart
        run: helm lint ${{ env.CHART_PATH }}

      - name: 5. Package Helm Chart
        run: |
          helm package ${{ env.CHART_PATH }}

      - name: 6. Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 7. Push Helm Chart to GHCR
        run: |
          CHART_FILE="${{ steps.chart_info.outputs.name }}-${{ steps.chart_info.outputs.version }}.tgz"
          
          echo "Pushing $CHART_FILE to oci://ghcr.io/${{ github.repository_owner }}/"
          helm push $CHART_FILE oci://ghcr.io/${{ github.repository_owner }}/

